### ISSUE TITLE
Workflows and documentation for how to work with Vaults when developing locally

### ISSUE THREAD

**Issue by earth2marsh** [apigee/apigee-access#3]
It isn't obvious how to work with secure Vault entries when deployed to Edge but also developing locally. If that workflow exists today, then maybe this is a docs problem, but perhaps it doesn't exist?

It might be handy if apigee-access knew whether it was running inside of Edge or not, and if not, then it could fall back to a local representation of things like Vault entries. Those entries could just be a standard JSON required into the project but that apigeetool knew not to deploy (and that was added to .gitignore).

**Comment by dzuluaga** [comment]
+1

**Comment by earth2marsh** [comment]
I'll update the docs for an example, but the issue about local dev still holds.
